### ISSUE TITLE
Use of Javanese fonts

### ISSUE THREAD

**Issue by NorbertLindenberg** [r12a/scripts#1]
The page javanese/index.html has a note near the top discussing the issues with Javanese fonts. The note itself and the style sheet for the document have issues that are at least partially related to each other:

– The note talks about "Firefox with Graphite rendering enabled". Since Firefox 49, Graphite has been enabled by default again. On the other hand, Firefox on iOS can’t use its own rendering engine; it has to use Webkit. So the appropriate description is “Firefox on platforms other than iOS”.

– The note says "An attempt to package the Tuladha Jejeg font as a webfont was unsuccessful". In fact, rendering with the tuladhajejeg_gr-webfont.woff2 font used by the page's style sheet fails, even in Firefox. The reason is likely that some conversion tool stripped out the Graphite tables – such stripping violates the WOFF specifications, but some converters do it anyway. One converter that works correctly is the ttx tool (https://github.com/fonttools/fonttools): Use it to convert the original .ttf file to .ttx, then convert the .ttx file to .woff using the "--flavor woff" option.

– Tuladha Jejeg is a widely used and accepted font, and probably the best choice for images of rendered text. Renderings must of course be made in Firefox on a platform other than iOS.

– Noto Sans Javanese, as the note says, is “over-simplified for some Javanese users”. It should only be used when no better option is available.

– The style sheet doesn’t make use of Javanese Text, which comes with Windows 8.1 and up, and is a good font in the style of Tuladha Jejeg.

– Yogyakarta doesn’t seem to be available anywhere anymore.

– The style sheet refers to a font family 'Noto Sans Javanese WF’, which doesn’t seem to be defined anywhere, while other parts use “webfont”.

Recommendation:

– Rebuild the WOFF versions of Tuladha Jejeg using the ttx tool. Once the WOFF fonts are proven to work in Firefox, remove the “(An attempt …)” part of the note.

– Change the “webfont” font-family name to 'Noto Sans Javanese WF' (unless there’s some dependency from JavaScript code).

– For the Javanese font-family, use: 'Javanese Text', Yogya, 'Noto Sans Javanese WF', serif. This makes use of two good fonts that may be present on Windows or iOS, respectively, before falling back to Noto Sans. Prefix with 'Tuladha Jejeg WF' if running in Firefox on platforms other than iOS. Rephrase the “The default webfont…” part of the note accordingly.

**Comment by r12a** [comment]
> – Rebuild the WOFF versions of Tuladha Jejeg using the ttx tool. Once the WOFF fonts are proven to work in Firefox, remove the “(An attempt …)” part of the note.

This requires me to download and install stuff, so i'm not able to do it at the moment.

> – Change the “webfont” font-family name to 'Noto Sans Javanese WF' (unless there’s some dependency from JavaScript code).

> – For the Javanese font-family, use: 'Javanese Text', Yogya, 'Noto Sans Javanese WF', serif. This makes use of two good fonts that may be present on Windows or iOS, respectively, before falling back to Noto Sans. Prefix with 'Tuladha Jejeg WF' if running in Firefox on platforms other than iOS. Rephrase the “The default webfont…” part of the note accordingly.

Done, and thanks for the prompt (i was planning to do that anyway, but hadn't gotten around to it).
