### ISSUE TITLE
[Tifinagh] Some diagraphs' phonetic transcription is incorrect

### ISSUE THREAD

**Issue by HannoMartinus** [r12a/scripts#114]
The phonetic value of these diagraphs should be [ts], [dz], [tʃ], [dʒ].

![image](https://user-images.githubusercontent.com/84947849/156011274-cb716285-7e07-4710-bc10-73cfa48a916b.png)

**Comment by r12a** [comment]
@HannoMartinus do you have a pointer to somewhere that explains that?  Thanks.

**Comment by r12a** [comment]
Ah, i see.  This is a mistake of the tooling.  I'll try to fix that.

**Comment by HannoMartinus** [comment]
@r12a I found this in page 30 of this document: [ISO/IEC JTC 1/SC 2/WG 2 N2739R](http://std.dkuug.dk/jtc1/sc2/wg2/docs/n2739.pdf)
![image](https://user-images.githubusercontent.com/84947849/156036952-26435223-a695-4842-900a-ac5066e2d364.png)

**Comment by r12a** [comment]
Thanks for the pointer.  The tifinagh page is an old one, from the times when i didn't point to source all the time. I have added links to Patrick's document for that section.  I also reworked a good deal of the page, including introducing a new high-level approach i've been wanting to try for some time.  So thanks for the prompt.
