### ISSUE TITLE
[hebr/he] strange to mark meteg as archaic

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#135]
[source] https://r12a.github.io/scripts/hebr/he

05BD (meteg) is labelled "archaic". No other mark has this "archaic" label. I see no way in which meteg is any more archaic than the other marks, and indeed I see some ways in which it is less archaic.

The way meteg is less archaic is because it is often used in text whose only other marks are vowel marks.  In this context, it is typically used to indicate primary stress when primary stress is nonfinal.

This style of marking (vowels plus meteg for nonfinal stress) is very common in prayerbooks.

I'm not sure how common this use of meteg is in vowel-pointed modern Hebrew texts meant for children and/or adult Hebrew learners.

**Comment by r12a** [comment]
> This style of marking (vowels plus meteg for nonfinal stress) is very common in prayerbooks.
> 
> I'm not sure how common this use of meteg is in vowel-pointed modern Hebrew texts meant for children and/or adult Hebrew learners.

thanks @bdenckla.  I suspect that i need to do a better job of describing the scope of the page.  My intention was to focus on modern Israeli usage, including texts meant for education and covering the use of niqqud for clarification of vowel sounds (educational or not), but excluding use for prayer books or religious books.  I actually thought i had some text to that effect, but looking now i see that i don't.

My knowledge of Hebrew is very limited compared to other scripts (such as Arabic), so i'm relying on sources for much of this information. I think, in this case, the information was largely from https://en.wikipedia.org/wiki/Meteg which describes meteg as primarily used in biblical Hebrew.  Do you think it's also used for modern, day to day Israeli text?

**Comment by bdenckla** [comment]
> I think, in this case, the information was largely from https://en.wikipedia.org/wiki/Meteg which describes meteg as primarily used in biblical Hebrew. Do you think it's also used for modern, day to day Israeli text?

There are two separate issues here:

* The primary issue is that _meteg_ is no more archaic than the marks that surround it in that table, which are all cantillation marks. (See screen snip below.) Regardless of how prevalent the use of _meteg_ is in pointings of modern Hebrew, it is certainly no more archaic than the cantillation marks, which **certainly** are not used in pointings of modern Hebrew.
* A secondary, minor point is how prevalent is the use of _meteg_ in pointings of modern Hebrew. I will try to do some research on that soon, to assess how common _meteg_ use is in vowel-pointed modern Hebrew texts meant for children and/or adult Hebrew learners.

![image](https://user-images.githubusercontent.com/941315/231530210-5d357e40-4615-4c65-8b0a-f32a0b83a6b1.png)

**Comment by r12a** [comment]
I think the primary issue here has been fixed.  If you find that meteg is used in Israeli Hebrew let me know. Closing for now.

**Comment by bdenckla** [comment]
Yes I agree, the primary issue has been addressed: meteg (U+05BD) is no longer presented as archaic compared to cantillation marks:

![image](https://user-images.githubusercontent.com/941315/232332559-365c0220-b287-441f-8f00-a6c0ec44bdf8.png)

The secondary issue is just that, secondary, and by a long gap in importance from the primary to it. Indeed I will let you know if I find some time to see if I can find some examples of modern Hebrew whose pointing includes _meteg_.
