### ISSUE TITLE
[hebr/he] HHFV & QQ aren't cantillation marks

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#137]
[source] https://r12a.github.io/scripts/hebr/he

The following are included in the list of cantillation marks, but they should be included in the list of vowels.

U+05BA: HEBREW POINT HOLAM HASER FOR VAV
U+05C7: HEBREW POINT QAMATS QATAN

This issue is sort of redundant with (or, to put it more charitably, is sort of the complement of) issue #134.

**Comment by r12a** [comment]
I removed these characters from the section that included cantillation marks, and added them to the section on [niqqud](https://r12a.github.io/scripts/hebr/he.html#combiningV), while noting that they are typically used for biblical text or prayer books, rather than the regular modern Israeli Hebrew writing we are discussing on this page.

**Comment by bdenckla** [comment]
I think this is a big improvement, to have HHFV & QQ moved from the "cantillation & misc." category to the section on niqqud.

But, I'm not sure your claim is correct that they are not typically used to point modern Hebrew. You could be right, I just don't know. I.e. it would require further research, as with #135, to know. If you don't have a good source saying they aren't use, I think it would be safer to assume that they are used to point modern Hebrew. They certainly could be used to point modern Hebrew, unlike, for example, cantillation marks.

The distinctions these two marks make are typographically subtle but phonetically quite dramatic, particularly in the case of HHFV.

I'm not sure what you mean the phrase "in usage" to means "to preserve fine typographic differences in usage."

Does "usage" refer to phonetics, i.e. sounds?
