### ISSUE TITLE
[hebr/he] vav is the only ML that takes a diacritic

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#138]
[source] https://r12a.github.io/scripts/hebr/he

The page currently says:

> Vowel locations can be marked by 4 [matres lectionis](https://r12a.github.io/scripts/glossary/index.html#materlectionis) (consonants indicating vowel locations), which also take diacritics in vowelled text.

I fear this could be misleading. Although of course the ML letters can take diacritics, they take diacritics precisely when and only when they are **not** functioning as MLs! (Except for _vav_.)

_Vav_ takes exactly one of the two diacritics precisely when and only when it **is** functioning as an ML:

* _ḥolam male_ dot
* _shuruq_ dot

I'm not sure exactly what definition of "diacritic" you mean to use here, so maybe you wouldn't even consider one or both of those two to be diacritics. They are not vowel markings in the strict sense that _ḥiriq_, _pataḥ_, _shuruq_, etc. are.

In texts that use HHFV (i.e. in most texts), U-ḤOLAM on _vav_ represents (and only represents) a _ḥolam male_ dot.

The situation is not so simple with _shuruq_ dot. Here Unicode took a somewhat concrete or visual approach to encoding rather than a more abstract or semantic approach: Unicode conflates several semantically-distinct central dots in a single code point, U-DAGESH OR MAPIQ. One of these conflated dots is the _shuruq_ dot. In other words, one cannot tell, without context, whether U-DAGESH OR MAPIQ on _vav_ represents a _dagesh_ or a _shuruq_ dot. All one knows is that it certainly isn't a _mapiq_.

**Comment by r12a** [comment]
In the new version of the summary the phrase 'which also take diacritics in vowelled text" is removed.
