### ISSUE TITLE
[hebr/he] ayin not an ML; he is

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#139]
[source] https://r12a.github.io/scripts/hebr/he

The page currently says:

> Hebrew uses the following consonant letters to indicate the location of a vowel.

And then proceeds to list _alef_, _ayin_, _vav_, & _yod_.

From what source does this list come?

My perception is that excluding _he_ from this list is wildly nonstandard, perhaps objectively wrong.

There might be more debate about whether _ayin_ should be included, but it is certainly nonstandard to include it.

The question of whether, in practice, _ayin_ is sometimes (or perhaps even always) an ML is just that, a question of practice.

In theory, at least in Biblical Hebrew, _ayin_ is never an ML.

Perhaps I should make a separate issue for this, but the page then goes on to say:

> The first two [_alef_ & _ayin_] are silent vowel supports, whereas the second two [_vav_ & _yod_] are considered to be part of the vowel.

I can't say this is wrong, because I don't understand what it means. I don't understand, and have never come across, this distinction between the following:

* being (merely?) a "silent vowel support"
* being considered to be part of the vowel

From what source does this distinction come?

**Comment by r12a** [comment]
The source is https://en.wikipedia.org/wiki/Hebrew_alphabet#Matres_lectionis

**Comment by bdenckla** [comment]
Sorry, in this case Wikipedia is not a reliable source. For contrast even on Wikipedia itself, see https://en.wikipedia.org/wiki/Mater_lectionis#Usage_in_Hebrew.

I'm pretty confident I can produce references to reams of printed matter that support "my" (and that page's) set of four letters (with _he_ not _ayin_). If you'd like, I can find you a few references, but I don't have time to accumulate references to the reams-quantity I claim is possible.

**Comment by bdenckla** [comment]
Also see https://en.wikipedia.org/wiki/Hebrew_spelling, which says, from the outset:

> An early system to overcome this [lack of dedicated vowel letters], still used today, is [matres lectionis](https://en.wikipedia.org/wiki/Mater_lectionis), where four of these letters, [alef](https://en.wikipedia.org/wiki/Aleph), [he](https://en.wikipedia.org/wiki/He_(letter)), [waw](https://en.wikipedia.org/wiki/Waw_(letter)) and [yodh](https://en.wikipedia.org/wiki/Yodh) also serve as vowel letters.

**Comment by r12a** [comment]
I have added a new section: [Hebrew spellings](https://r12a.github.io/scripts/hebr/he.html#spelling)

And rewritten the following sections: [Matres lectionis](https://r12a.github.io/scripts/hebr/he.html#matres) and [Standalone vowels](https://r12a.github.io/scripts/hebr/he.html#standalone). 

Hopefully, that's an improvement.

**Comment by r12a** [comment]
I also made substantial changes to the descriptions of the 4 matres lectionis in the character notes. See
https://r12a.github.io/scripts/hebr/block.html#char05D0
https://r12a.github.io/scripts/hebr/block.html#char05D4
https://r12a.github.io/scripts/hebr/block.html#char05D5
https://r12a.github.io/scripts/hebr/block.html#char05D9

There were also major changes to the vowel-to-character mapping tables:
https://r12a.github.io/scripts/hebr/he.html#vowel_mappings

**Comment by r12a** [comment]
I think this is fixed. Reopen if needed.
