### ISSUE TITLE
[hebr/he] maqaf does not indicate one breath

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#140]
[source] https://r12a.github.io/scripts/hebr/he

The page currently says:

> maqaf [...] indicates a combination of 2 or more words that are pronounced in one breath

This notion stems, I think, from a mistranslation in another comment on another issue in another repo: the hlreq repo. I address this problem in my own comment on that other issue in the hlreq repo: https://github.com/w3c/hlreq/issues/8#issuecomment-1506950185

As a short summary, I think it would be better to either not try to define the cantillation function of _maqaf_, or to define it as something like:

> _maqaf_ indicates a combination of 2 or more words forming a compound word, which like any word, needs no more than one accent.

**Comment by r12a** [comment]
The description of the cantillation function was removed.
