### ISSUE TITLE
[hebr/he] word-initial alef & ayin are not considered vowels

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#141]
[source] https://r12a.github.io/scripts/hebr/he

In the section called "Standalone vowels" (a concept I have never run across in relation to Hebrew), the page says:

> Word-initial [vowel sounds] that are not preceded by a consonant sound are represented by, or written in conjunction with, [_alef_] or [_ayin_].

As I mentioned in issue #139 with relation to _ayin_, although one may argue that in practice, in some dialects and/or contexts these are pronounced only as a vowel sound, i.e., are not accompanied by a glottal stop, these are, nonetheless, conceived of as (theorized as) glottal stop consonants, not vowels, when they are word-initial. (_Ayin_ always, not just when it is word-initial, in fact: that's my point in #139. _Alef_ is conceived of as a glottal stop in only some of its non-initial appearances; at other times it is an ML, i.e. corresponds to only a vowel sound.)

I think your job will be simplified, if you either don't worry about describing practice, or if you do describe practice, you do not neglect to describe theory as well, and carefully qualify which you are talking about (theory vs. practice).

As it is, to my ears, you are currently making claims that sound wrong according to theory, so they either look wrong to the reader, or the reader is required to assume that implicitly, you are referring to the pragmatics of some dialect and/or context.

It is trickier to make claims about practice, so if you do want to make them, IMO they need some authoritative sources. Theory (according to me at least) is more widely documented and agreed upon.

@skadish1 anything to add?

**Comment by bdenckla** [comment]
I think part of the problem is you may be confusing how words are commonly transcribed (transliterated) vs. what sounds those words are thought to have.

I gain this perspective from, for example, https://r12a.github.io/scripts/hebr/block.html#he05D0, where, in a section pretty clearly transcribing the sound of _alef_ as a glottal stop (ʔ), it mentions, quite correctly, that _alef_ is usually not transcribed in word-initial position:

> ʔ eg.
> אֵם em mother
> In word-initial position, alef is not usually transcribed, eg. the transcription of the previous example would be em.

![image](https://user-images.githubusercontent.com/941315/231789554-eefbf78b-5a81-43b5-9f89-edcef908111e.png)

Not all transcriptions (in fact very few) try to capture the complete phonetics of the source script. As such, they should not be taken to imply an interpretation of the phonetics of the source script. It is quite reasonable for all but the most technical of transcriptions to omit initial glottal stops. It is not reasonable to take this omission to mean that these sounds do not exist, at least in theory.

**Comment by r12a** [comment]
I rewrote the [Standalone vowels](https://r12a.github.io/scripts/hebr/he.html#standalone) section.

**Comment by r12a** [comment]
I think this is fixed. Reopen if needed.
