### ISSUE TITLE
[hebr/he] example of ḥolam male looks like ḥolam ḥaser

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#142]
[source] https://r12a.github.io/scripts/hebr/he

Although the code points are correct (U-HOLAM not U-HHFV), whatever font is being used (on my system at least) sure looks like it is doing U-HHFV-like positioning:

![image](https://user-images.githubusercontent.com/941315/231781548-0e207c63-c7bf-4176-99dd-87263f6798d3.png)

Compare U-HHFV (right) vs U-HOLAM in a correctly-behaving font:

![image](https://user-images.githubusercontent.com/941315/231782526-31dd28c3-2868-490e-be41-8ab3082fe575.png)

(Note that U-HHFV is "illegal" in this context, but I'm just using it for purposes of illustration.)

**Comment by r12a** [comment]
This was fixed by updating the webfont to the latest Noto version.

<img width="637" alt="Screenshot 2023-04-16 at 07 40 25" src="https://user-images.githubusercontent.com/4839211/232277628-ce8e12b4-239a-4863-810f-4077c1e337db.png">
