### ISSUE TITLE
[hebr/he] example of pataḥ has no pataḥ

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#143]
[source] https://r12a.github.io/scripts/hebr/he

![image](https://user-images.githubusercontent.com/941315/231782957-31207f7e-6a34-4b8a-a66c-5f69b8da92a0.png)

**Comment by r12a** [comment]
Fixed.

<img width="436" alt="Screenshot 2023-04-16 at 07 47 29" src="https://user-images.githubusercontent.com/4839211/232278128-5bec2a7d-3f51-4681-90eb-a0724df949bb.png">
