### ISSUE TITLE
[hebr/he] example of maqaf missing initial tav?

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#144]
[source] https://r12a.github.io/scripts/hebr/he

The example given is ל־אביב. Image:

![image](https://user-images.githubusercontent.com/941315/231783857-bd98c84e-edbd-4740-9e95-706a806e22fe.png)

I suppose there's nothing wrong with that example, although I don't know what, if anything, it means.

Did you perhaps mean תל־אביב (Tel-Aviv)?

**Comment by r12a** [comment]
This was indeed intended to be Tel-Aviv. Somehow became corrupted. Now fixed.
