### ISSUE TITLE
[hebr/he] 4 not 3 MLs

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#145]
[source] https://r12a.github.io/scripts/hebr/he

In the short section "Matres lectionis", the page says:

> Three of the letters can also represent vowel locations.

There are generally agreed to be 4 MLs, not 3. As to what those four are, that's a separate issue: see #139.

**Comment by r12a** [comment]
Having immersed myself in Hebrew terms for a week i plan to rewrite the part of the orthography notes that describes vowel representation. Closing this in favour of 139.
