### ISSUE TITLE
[hebr/he] example cantillation text has poor mark placement

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#146]
[source] https://r12a.github.io/scripts/hebr/he

Original:

![image](https://user-images.githubusercontent.com/941315/231793654-344ba0d6-6b3e-419a-b6f6-026e3ef87b05.png)

With blue arrows highlighting the two placement issues:

![Genesis r12a trope placement issues](https://user-images.githubusercontent.com/941315/231796047-97e90750-3a2c-4216-81f4-f0871e1b17cd.png)

Example of text without these issues:
![image](https://user-images.githubusercontent.com/941315/231796142-f021bf5e-0314-4b40-bd49-becc8dd480fe.png)
![image](https://user-images.githubusercontent.com/941315/231796161-0d10e18f-da2b-4593-a6ba-77463dbe6f0e.png)

**Comment by r12a** [comment]
The page uses a Noto Serif Hebrew webfont. 

Btw, i can't tell whether this should be 0599 HEBREW ACCENT PASHTA or 05A8 HEBREW ACCENT QADMA. It makes a difference in Ezra SIL SR, Times New Roman and Tahoma.

Which font and code point are you using?

**Comment by bdenckla** [comment]
Wait but here we're talking about an image generated using what is probably different font than the font used on the page for real text, right? And then coloring was added, which is probably what messed up the mark placement, since in general it is impossible to add coloring to marks without messing up placement, although I know specific people who have had success with adding color, using specific software and specific techniques within that software.

As for whether that mark on the _tav_ should be created by U-PASHTA or U-QADMA... that's a darn good question, one I get into in #157. Semantically (abstractly), it should be U-PASHTA. But concretely, visually, placement-wise, U-QADMA is a "cheat" to get the central placement you want without requiring the font to be "smart". As I mentioned above, I suspect the coloring defeated the font's "smarts", so this might be one rare case where I would, regrettable, advise to use U-QADMA. And then once you've generated the image, destroy the Unicode source file evidence.

Perhaps a good approach to generating small examples where only marks are colored, like this, would be to generate an SVG and then edit the resulting SVG in an SVG editor. I think harfbuzz has a utility that will generate an SVG from a string; there's probably other software that can do it as well. I guess any SVG editor will allow you to put text in and then created an SVG from that and then you could import that SVG back into the SVG editor and manipulate the color of the marks there.

**Comment by bdenckla** [comment]
As to what font I used to create the image I provided, I am using my own font, https://bdenckla.github.io/Taamey_D/.

**Comment by r12a** [comment]
The colourisation didn't change anything.  I create the text in a web page, then take a screen grab in the highlight colour, then change the colour (of the whole thing), and screen grab again.  Then in PhotoShop i place one image over the other and delete where the highlight needs to shine through.  So no effect at all on placement.

Usually i record the actual font used and the size in the image element attributes, but this is an old image dating from before i did that consistently :(

**Comment by bdenckla** [comment]
> I create the text in a web page, then take a screen grab in the highlight colour, then change the colour (of the whole thing), and screen grab again. Then in PhotoShop i place one image over the other and delete where the highlight needs to shine through. So no effect at all on placement.

Interesting technique!

**Comment by r12a** [comment]
I replaced the image with a new one, using the Ezra SIL SR font which allowed me to use the correct code points and (hopefully) produces something close enough to what's expected. (Click on the image, as usual for recent figures, to see the composition.)

https://r12a.github.io/scripts/hebr/he.html#fig_diacritics

**Comment by bdenckla** [comment]
The new image looks great. SIL Ezra is a great choice for this. I like the new coloring where cantillation marks have a different color that other marks. Pasting the image in here just to have a one-stop record of what we're talking about.

![image](https://user-images.githubusercontent.com/941315/232239073-b80a6ba6-be81-4cb9-92e1-0203593a3683.png)
