### ISSUE TITLE
[hebr/he] why is vav ML only identified with 'u' sound?

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#148]
[source] https://r12a.github.io/scripts/hebr/he

![image](https://user-images.githubusercontent.com/941315/231805274-1458217a-7fce-4ab4-b7a6-ebdd8b16f16f.png)

What about the 'o' sound it can represent. (I'm not sure what the appropriate IPA would be for that 'o' sound, but you get the idea.)

I.e. you seem to only be representing vav's role as _shuruq_, ignoring its role as _holam_.

**Comment by r12a** [comment]
Fixed.

<img width="54" alt="Screenshot 2023-04-16 at 07 53 56" src="https://user-images.githubusercontent.com/4839211/232278530-52047e15-c5ee-4960-870e-e4468c7b84bc.png">
