### ISSUE TITLE
[hebr/he] why is the 'ju' dipthong unpointed?

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#149]
[source] https://r12a.github.io/scripts/hebr/he

![image](https://user-images.githubusercontent.com/941315/231806353-f53dc60e-c650-4781-af1a-3c3b361372ac.png)

I'm not that familiar with thinking about this as a dipthong, but I have no reason to believe it is wrong to do so.

What strikes me as possibly wrong, or at least surprising, is that there is no dot turning the _vav_ into a _shuruq_, i.e. there is no U-DAGESH OR MAPIQ "in" the _vav_.

Whereas, you've pointed all the other examples (except for או, which I'm not familiar enough with to suggest how to point it).

**Comment by r12a** [comment]
Fixed 

<img width="165" alt="Screenshot 2023-04-16 at 08 38 23" src="https://user-images.githubusercontent.com/4839211/232280878-8f816ebc-27af-4fde-a36b-37c3211a2057.png">
