### ISSUE TITLE
[hebr/he] why does kaf get its dagesh variant sound but others do not

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#150]
[source] https://r12a.github.io/scripts/hebr/he

![image](https://user-images.githubusercontent.com/941315/231807659-ec57c951-546b-4272-9994-ad6cb96cf3a0.png)

Why does _kaf_ get both of its sounds listed (x & k) but _pe_ and _bet_ do not. I.e.,

- _pe_ gets only the f sound listed (no p, i.e. it lacks its "namesake" sound)
- _bet_ gets only the v sound listed (no b, i.e. it lacks its "namesake" sound)

Are the contrasts from f to p and v to b viewed as not as significant as the contrast from x to k (and s to ʃ), and therefore they didn't "make the cut" in this list? I suppose I can understand that, although it is quite confusing to have such an implicit criteria operating. Or am I giving you too much benefit of the doubt and this is just an oversight?

These missing sounds are represented in the section on _dagesh_.

**Comment by r12a** [comment]
<img width="113" alt="Screenshot 2023-04-16 at 08 48 32" src="https://user-images.githubusercontent.com/4839211/232282599-4a1460b4-a5f5-475b-8486-efa85cf8d47b.png">
