### ISSUE TITLE
[hebr/he] why is k a possible sound of a kaf explicitly lacking a dagesh?

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#151]
[source] https://r12a.github.io/scripts/hebr/he

![image](https://user-images.githubusercontent.com/941315/231810507-c87f697b-d15f-48ec-b36d-8057823b8ef8.png)

I.e. I would have expected that x be the only sound listed for a _kaf_ explicitly lacking dagesh, i.e. a _khaf_ (note kh not k).

**Comment by r12a** [comment]
Now shows

<img width="487" alt="Screenshot 2023-04-16 at 08 54 45" src="https://user-images.githubusercontent.com/4839211/232283407-2b9b6e54-a213-4d8f-8968-c8a966471d71.png">

which reflects that these consonants with a dagesh represent only one sound, but in unpointed text they represent one of two different possibilities. (The surrounding text could be modified to indicate that the sound/form relationship shown should be read as purely in a context which is pointed, but i thought the current presentation would be clearer and shorter.)
