### ISSUE TITLE
[hebrew/block] links to character app broken?

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#153]
[source] https://r12a.github.io/scripts/hebrew/block

Some (all?) links to the "character app" are broken", e.g. https://r12a.github.io/pickers/hebrindex.html?text=%D7%90.

Accessed from, for example (image):

![image](https://user-images.githubusercontent.com/941315/231818231-2a8f3bf1-80ab-45ae-b944-8aa6c1e3ffba.png)

**Comment by r12a** [comment]
Thanks for the reminder to fix that. 

Should be ok now. (Reopen if not.)

**Comment by bdenckla** [comment]
Works now for me!
