### ISSUE TITLE
[hebrew/block] final pe does take dagesh in one Biblical word

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#155]
[source] https://r12a.github.io/scripts/hebrew/block

This page claims:

> There is no final variant form for [_pe_] letter when used to represent [the sound] p, the regular form is always used, eg. compare the last example [שׁוֹפּ] with [שׁוּף]

Final pe does take _dagesh_ in one Biblical word, תּ֥וֹסְףְּ, part of the _maqaf_ compound אַל־תּ֥וֹסְףְּ in [Proverbs 30:6](https://bdenckla.github.io/MAM-with-doc/D2-Proverbs.html#c30v6) (משלי ל,ו).

![image](https://user-images.githubusercontent.com/941315/231831350-f0bb9af6-2390-4077-a054-96a1a0e3df0b.png)

I am not sure whether there are any exceptions in modern Hebrew, but I feel it would be better to either specifically cite this example, or soften your claim.

**Comment by r12a** [comment]
Added a note:

<img width="533" alt="Screenshot 2023-04-16 at 11 13 18" src="https://user-images.githubusercontent.com/4839211/232294358-e0fac88d-badc-44f4-be75-cae6217a29f5.png">

**Comment by bdenckla** [comment]
Great. Biblical nerds like me will rejoice.

**Comment by bdenckla** [comment]
Also, I have some suspicion that the need to a represent final p sound (as opposed to a final f sound) is mainly or solely in words of foreign origin. I.e. I have some suspicion that your "shop" example is actually the English word "shop", not a Hebrew word. I also just ran across this, in _The Routledge Introductory Course in Modern Hebrew_:

![image](https://user-images.githubusercontent.com/941315/232618124-853b3527-4bf8-45ae-80a0-539875b8216e.png)

So, okay, that's how words of foreign origin with a final p sound are written, but are there words of non-foreign origin that have a final p sound? And if so, how are they written?
