### ISSUE TITLE
[hebrew/block] cantillation marks are Israeli Hebrew?

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#156]
[source] https://r12a.github.io/scripts/hebrew/block

![image](https://user-images.githubusercontent.com/941315/231833622-5125ed8e-3ead-4c7b-8d3e-51e97cbfafdc.png)

Is it possible to classify them as Biblical Hebrew (language code hbo)?

**Comment by bdenckla** [comment]
Oh wait, I think I may have misunderstood what this "Israeli Hebrew" label is labelling. Judging from how it is used for the letters of the alphabet, "Israeli Hebrew" label is labelling the (pointed) spellings of the code point's name in Israeli Hebrew.

In other words, it seems that this label is not categorizing what language the code point belongs to, as I had originally thought.

So, I guess I'd amend my suggestion to be, not that "Israeli Hebrew" be changed to "Biblical Hebrew," but that "Israeli Hebrew" not appear at all, if there are no names to follow it!

(There certainly are names for these code points in modern Hebrew, but I don't think it is within the scope/goals you have to bother including these names.)

**Comment by r12a** [comment]
Yes, the boxes entitled Israeli Hebrew should describe only characters used in that orthography, and should not include things like cantillation marks that are not in that orthography.  I'm currently working on a fix for this which will remove the title "Isreali Hebrew" from things not deemed to be part of that orthography. 

 I'm also assessing whether or not to set up a new set of orthography notes that will have the title "Biblical Hebrew", and wondering (a) whether i have enough to say about those items, and (b) how to best avoid what may be largely duplication for characters in both.

**Comment by r12a** [comment]
See https://r12a.github.io/scripts/hebr/block and note the addition to the intro that says that the biblical Hebrew notes only represent deltas from the Israeli Hebrew (for now at least).

See the effect on https://r12a.github.io/scripts/hebr/block.html#char05E4

**Comment by r12a** [comment]
Crossing my fingers that this works well enough for now, i'll close this issue.

**Comment by bdenckla** [comment]
I see. So now the labels in question are now labels of subsections (usually only 1, but sometimes more than 1, as for _pe_) describing usage in Israeli Hebrew and/or Biblical Hebrew. Works for me.

**Comment by bdenckla** [comment]
Do you mean the Hebrew font to be (a) much smaller (b) a different font when the pointed Hebrew name is presented for a Biblical Hebrew section, e.g.

![image](https://user-images.githubusercontent.com/941315/232332150-3d710e13-4e61-40fc-a4d7-c1444bc2cc8a.png)

Or, perhaps better showing the contrast:

![image](https://user-images.githubusercontent.com/941315/232332181-14e11221-3892-4669-819d-985f87848dd7.png)

![image](https://user-images.githubusercontent.com/941315/232332183-df34c306-e48e-448f-b8e4-d0d9ccee8d2d.png)
