### ISSUE TITLE
[hebrew/block] NUN HAFUKHA is Biblical Hebrew

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#158]
[source] https://r12a.github.io/scripts/hebr/block.html

Currently it lacks a category, whereas most other marks are categorized as Israeli Hebrew or Biblical Hebrew (or in one case, (_pe_), both).

**Comment by r12a** [comment]
As for yod triangle, if i don't have any information to post about a character i leave the notes blank. It stays in the block.html file so that all characters have an entry stub - and carry Unicode descriptions, links to UniView, etc.
