### ISSUE TITLE
[hebrew/block] double vav ligature worthy of any note?

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#160]
[source] https://r12a.github.io/scripts/hebr/block.html

I think giving this code point a note may suggest that this code point is more useful than it actually is. My understanding is that it is just one of those many code points put in for compatibility with pre-Unicode character sets.

I.e. AFAIK there's no reason to not just use two _vav_ code points in a row, unless you want a one-to-one mapping with some pre-Unicode character set that had this as a single character.

The orthographic function of double _vav_, to represent the w sound in words outside modern Hebrew, is worth noting, but you already note that in the section on general orthography. Noting it here somehow suggests that double _vav_ should be (or is widely?) realized/implemented with this ligature. Do you have reason to believe that double _vav_ should be (or is widely?) implemented with this ligature?

Also, the example given is weird: עונטה.

There's no double _vav_ in it!

**Comment by r12a** [comment]
I agree.  I removed the notes.
