### ISSUE TITLE
[arab/ur]  Repeated characters in Urdu Punctuation List

### ISSUE THREAD

**Issue by aenaliph** [r12a/scripts#164]
I noticed that the following three punctuations are repeated in the Urdu Punctuations list at:
https://r12a.github.io/scripts/arab/ur.html#index_punctuation

- ARABIC PERCENT SIGN
- ARABIC DECIMAL SEPARATOR
- ARABIC THOUSANDS SEPARATOR

Currently this list reports 14 characters for Punctuations. Removing duplicates will make it 11.

Thanks for this resource.

**Comment by r12a** [comment]
Thanks @aenaliph.  Should be fixed now.
