### ISSUE TITLE
[nkoo/nqo] Sample language name is wrong

### ISSUE THREAD

**Issue by donaldsoncd** [r12a/scripts#167]
Comment on http://r12a.github.io/scripts/nkoo/

In the "Sample" section, the language is said to be "Mandinka":

![image](https://github.com/r12a/scripts/assets/28364193/101bdc45-6c08-4899-827b-54fca271bae4)

This is misleading since "Mandinka" generally refers to Mandinka as spoken in the Senegambia region (which has 5 vowels). The text is in "Maninka" as spoken in and around Guinea (with 7 vowels). This variety of Manding is commonly referred to as "malinké" in French and therefore it shows up in English as well.

**Comment by r12a** [comment]
Section title changed. Thanks for the poke !
