### ISSUE TITLE
[nkoo/nqo] Reference author's name missing (and potential citation missing)

### ISSUE THREAD

**Issue by donaldsoncd** [r12a/scripts#168]
Comment on http://r12a.github.io/scripts/nkoo/

In the reference section, the author of the first entry's ("Clear Language: Script, Register And The N’ko Movement Of Manding-Speaking West Africa") name is missing:

![image](https://github.com/r12a/scripts/assets/28364193/ef0ebec1-806c-4184-8321-2655b90f130f)

The author (who happens to be me haha) is Coleman Donaldson.

On that note, I think that a citation or source mention would be appropriate in the section about "N'ko and the Manding Koiné". For instance, there is a table in that section:

![image](https://github.com/r12a/scripts/assets/28364193/9acb0b00-df85-4a99-9189-74b32c0fea07)

It appears to be a reproduction of a table from my dissertation (p. 207) :

![image](https://github.com/r12a/scripts/assets/28364193/8fd8320a-b081-4447-a887-04a112a7e5ee)

**Comment by r12a** [comment]
Erk !   Thanks for spotting this, Coleman.  I made a bit of a hash of the updating, but you can see the updates at https://github.com/r12a/scripts/commit/3554913d0ce3d63b0c71a6aff1a8aa78645913da and https://github.com/r12a/scripts/commit/6fc94f8f443a45620bb62cf0f6e822e88fd68a18

The direct link i had to your dissertation no longer seems to work.  Do you have an alternative?

**Comment by donaldsoncd** [comment]
Thanks!

The permalink, according to Penn, is the following: https://repository.upenn.edu/handle/20.500.14332/29701

**Comment by r12a** [comment]
Fixed !
