### ISSUE TITLE
Incorrect statement in Javanese shaping examples

### ISSUE THREAD

**Issue by NorbertLindenberg** [r12a/scripts#2]
The last paragraph of the "shaping" section of javanese/index.html incorrectly refers to a "k-k" conjoined shape. It's in fact a "k-s" conjoined shape, derived from ka and sa mahaprana.

It may be worth pointing out that the third cluster uses a true ligature of cakra and u, with the u drawn before the cakra that it logically follows.

**Comment by r12a** [comment]
Fixed by https://github.com/r12a/scripts/commit/16de53b846132c3dbfbb67b0c111c850f606e03e. Thanks.
