### ISSUE TITLE
Refresh font list when changing OS checkboxes

### ISSUE THREAD

**Issue by Lorp** [r12a/scripts#49]
It would be nice if the font list refreshes whenever a user changes the state of a checkbox (or other UI that would change the font list in any way).

**Comment by r12a** [comment]
Thanks for the nudge.  I had also been thinking about that.  

I enabled it for the selection of Mac/Win/Noto/SIL. Not yet for the show text/show graphics checkboxes.

The font sizing and wrapping already work.

**Comment by Lorp** [comment]
Nice, thanks!
