### ISSUE TITLE
[tibetan summary] Typo in tsek padding test paragraph

### ISSUE THREAD

**Issue by epigraphic** [r12a/scripts#6]
Comment on https://r12a.github.io/scripts/tibetan/ 

In the Tibetan test paragraph at the end of § Method 2: tsek padding, there is an unexpected NBS character between the base ga and the naro vowel mark.  i.e.  བྱེདདག ོ ---> བྱེདདགོ

**Comment by epigraphic** [comment]
Typo is in https://github.com/r12a/scripts/blob/gh-pages/tibetan/index.html
འདྲ་མཉམ་གྱི་རྒྱབ་གཉེར་སྲུང་སྐྱོབ་བྱེདདག&#xA0;ོས་པའི་ཐོབ་དབང་ཡོད།

**Comment by r12a** [comment]
Should be fixed now. Thanks for reporting.
