### ISSUE TITLE
Sublime text shows compound letter as splitted - Malayalam Language

### ISSUE THREAD

**Issue by bsde1234** [r12a/scripts#61]
When I try to open file containing malayalam words, sublime text shows compound letters as splitted letters. For example the word `ഉത്തരം` shows as `ഉത് തരം` without space in it. PS: I can't write here without space as it will show as normal compound letter.
But in Visual studio code, it works correctly. Can you please tell me where is the problem. Thanks.

**Comment by r12a** [comment]
If you can see Malayalam characters at all, Subime Text must be falling back to a malayalam font, but (a) that font may not support the required opentype shaping, or (b) Sublime Text may be blocking/lacking access to the external shaping algorithms that the font relies on.  I don't use ST, but you could check to see whether the preferences allow you to specify a particular font for malayalam text.

Ultimately, however, if you are writing Web pages, as long as you enter the malayalam text correctly, even though it doesn't look good in ST it should still look ok in the browser, as long as you declare the language in the lang attribute and apply or fall back to a reasonable font.

**Comment by bsde1234** [comment]
I am working with Meera font which shows correctly in Libre office as `ഉത്തരം`. So I think it is not related to font. I think Sublime lacking access to external shaping algorithms. Actually I need this feature with Imagemagick to draw text as image which now produces `ഉത് തരം` in image. Is there any easyway to fix this. I am in contact with developer of Imagemagick, he is not seems to be aware of this feature. What message should I give to him to fix this.
