### ISSUE TITLE
[tibetan summary] Inaccurate categorization of U+0F3E and U+0F3F

### ISSUE THREAD

**Issue by dscorbett** [r12a/scripts#7]
The “Bracketing information” section says:
>  ༾ [U+0F3E TIBETAN SIGN YAR TSHES​] and  ༿ [U+0F3F TIBETAN SIGN MAR TSHES​] are also paired characters used in combination with digits.

Do they belong in this section? According to [this manual](https://collab.its.virginia.edu/access/content/group/26a34146-33a6-48ce-001e-f16ce7908a6a/Tibetan%20fonts/Tibetan%20Legacy%20Fonts/Tibetan!.pdf#page=94), U+0F3E and U+0F3F go on numbers to mark the waxing and waning periods of the month. It doesn’t sound like they are used together to bracket anything.

**Comment by r12a** [comment]
Thanks for pointing that out. Fixed in the commit just above.
