### ISSUE TITLE
[fontlist]  Old Persian sample

### ISSUE THREAD

**Issue by r12a** [r12a/scripts#78]
[source] https://r12a.github.io/scripts/fontlist

> Here's some Old Persian from the Behistun inscription I typed a while ago:
> 𐏑𐎶𐎼𐎫𐎡𐎹𐏐𐎶𐎦𐎢𐏁𐏐𐎠𐏃𐏐𐎥𐎢𐎶𐎠𐎫𐏐𐎴𐎠𐎶
>  
> Is that the length you need, or do you need longer?

Thanks @roozbehp!  Ideally, i'd prefer twice that length.  Do you have more?  Something, however, is much better than nothing.

**Comment by roozbehp** [comment]
Ok, here is the opening to the Behistun inscription, its first full sentence:

𐏐𐎠𐎭𐎶𐏐𐎭𐎠𐎼𐎹𐎺𐎢𐏁𐏐𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐏐𐎺𐏀𐎼𐎣𐏐𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐏐𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐎠𐎴𐎠𐎶𐏐𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐏐𐎱𐎠𐎼𐎿𐎡𐎹𐏐𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐏐𐎭𐏃𐎹𐎢𐎴𐎠𐎶𐏐𐎻𐏁𐎫𐎠𐎿𐎱𐏃𐎹𐎠𐏐𐎱𐎢𐏂𐏐𐎠𐎼𐏁𐎠𐎶𐏃𐎹𐎠𐏐𐎴𐎱𐎠𐏐𐏃𐎧𐎠𐎶𐎴𐎡𐏁𐎡𐎹

Translation:

I am Darius, the great king, the king of kings, the king of Persia, the king of the provinces, the son of Hystaspes, the grandson of Arsames, the Achaemenian.

**Comment by r12a** [comment]
Excellent, thanks!  I added the new text.
