### ISSUE TITLE
404 for block/block-code.js

### ISSUE THREAD

**Issue by NorbertLindenberg** [r12a/scripts#8]
Go to https://r12a.github.io/scripts/indic-overview/
Look for “ You can try it now by clicking on the following”. Click on the following Devanagari character sequence. Nothing happens. 
Open the Web Inspector (Safari), Web Console (Firefox), or equivalent. Notice that there's an error message that
https://r12a.github.io/scripts/block/block-code.js
could not be loaded.

**Comment by r12a** [comment]
Thanks Norbert.  I updated the template, so hopefully things now work again.  (I did it quite quickly, so i'm hoping that i didn't break something else...)
