### ISSUE TITLE
[fontlist]  Sample Manichean text

### ISSUE THREAD

**Issue by roozbehp** [r12a/scripts#80]
[source] https://r12a.github.io/scripts/fontlist

This is all I have, from L2/11-123R (https://www.unicode.org/L2/L2011/11123r-n4029r-manichaean.pdf), Figure 6:

𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅
𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶
𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓

**Comment by r12a** [comment]
Added. More thanks!

https://r12a.github.io/scripts/fontlist/?script=mani#result
