### ISSUE TITLE
[fontlist] Ogham script sample

### ISSUE THREAD

**Issue by roozbehp** [r12a/scripts#82]
[source] https://r12a.github.io/scripts/fontlist

This is the longest Ogham text I could find, from the Book of Leinster:

᚛ᚌᚔᚚ ᚓ ᚈᚔᚄᚓᚇ ᚔᚅ ᚃᚐᚔᚇᚉᚆᚓ᚜ ᚛ᚇᚘᚐ ᚋᚁᚐ ᚌᚐᚄᚉᚓᚇᚐᚉᚆ᚜
᚛ᚌᚓᚔᚄ ᚃᚐᚔᚏ ᚐᚏ ᚈᚆᚓᚉᚆᚈ ᚇᚔᚅᚇ ᚃᚐᚔᚇᚉᚆᚔ᚜
᚛ᚉᚓᚅ ᚉᚆᚑᚋᚏᚐᚉ ᚅᚑᚓᚅᚃᚆᚔᚏ ᚇᚑ ᚃᚆᚒᚐᚉᚏᚐ᚜

Translation:
Whoever comes to this meadow, if he be armed, he is forbidden to leave the meadow, without requesting single combat.

**Comment by r12a** [comment]
Done!
https://r12a.github.io/scripts/fontlist/?script=ogam#result
