### ISSUE TITLE
[fontlist] Sample Avestan text

### ISSUE THREAD

**Issue by roozbehp** [r12a/scripts#83]
[source] https://r12a.github.io/scripts/fontlist

Here is some Young Avestan sample from Mihr-Yašt:

𐬨𐬭𐬀𐬊𐬝. 𐬀𐬵𐬎𐬭𐬋. 𐬨𐬀𐬰𐬛𐬃. 𐬯𐬞𐬪𐬙𐬀𐬨𐬁𐬌. 𐬰𐬀𐬭𐬀𐬚𐬎𐬱𐬙𐬭𐬁𐬌𐬺 𐬁𐬀𐬝. 𐬫𐬀𐬝. 𐬨𐬌𐬚𐬭𐬆𐬨. 𐬬𐬊𐬎𐬭𐬎. 𐬔𐬀𐬊𐬌𐬌𐬀𐬊𐬌𐬙𐬍𐬨. 𐬟𐬭𐬀𐬛𐬀𐬜𐬄𐬨. 𐬀𐬰𐬆𐬨. 𐬯𐬞𐬌𐬙𐬀𐬨𐬀. 𐬁𐬀𐬝. 𐬛𐬌𐬨. 𐬛𐬀𐬜𐬄𐬨. 𐬀𐬎𐬎𐬃𐬧𐬙𐬆𐬨. 𐬫𐬈𐬯𐬥𐬌𐬌𐬀𐬙𐬀. 𐬀𐬎𐬎𐬃𐬧𐬙𐬆𐬨. 𐬬𐬀𐬵𐬨𐬌𐬌𐬀𐬙𐬀. 𐬫𐬀𐬚𐬀. 𐬨𐬄𐬨𐬗𐬌𐬝. 𐬫𐬌𐬨. 𐬀𐬵𐬎𐬭𐬀𐬨. 𐬨𐬀𐬰𐬛𐬄𐬨.𐬺

Translation:
Said Ahura Mazdāh to Zarathuštra the Spitamid: ‘When I created grass-land magnate Mithra, O Spitamid, I made him such in worthiness to be worshipped and prayed to as myself, Ahura Mazdāh.’

**Comment by r12a** [comment]
Done !
https://r12a.github.io/scripts/fontlist/?script=avst#result
