### ISSUE TITLE
[fontlist] Old South Arabian sample

### ISSUE THREAD

**Issue by roozbehp** [r12a/scripts#85]
[source] https://r12a.github.io/scripts/fontlist

From a construction inscription housed in British Museum, in early middle Sabaic language:

𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬
𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽 𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺
𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩
𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠

Image:

![B_res3913_b](https://user-images.githubusercontent.com/302255/108575645-c727c080-72cf-11eb-95bf-67137964655d.jpg)

Translation:

Lḥyʿṯt S¹ṭrn, kabir of Fayshān, built, and laid foundations and completed two canals, those of the three dams for his two palm groves Mṭrt and Mwhrh; by ʿAthtar and by Almaqah.

**Comment by r12a** [comment]
Done !
https://r12a.github.io/scripts/fontlist/?script=sarb#result

Many thanks for your help, @roozbehp .
