### ISSUE TITLE
[fontlist]  Bhaikshuki Sample

### ISSUE THREAD

**Issue by virtualvinodh** [r12a/scripts#86]
[source] https://r12a.github.io/scripts/fontlist

I guess I missed Bhaikshuki. 

𑰁𑰫𑰿𑰓𑰨𑰿𑰧𑰽𑱃𑰫𑰲𑰟𑰿𑰠𑰭𑰝𑰿𑰝𑰿𑰪𑰭𑰿𑰧𑱃𑰩𑰺𑰎𑰸𑱃𑰩𑰺𑰎𑰯𑰡𑰲𑰪𑰨𑰿𑰝𑰰𑰡𑰺𑱁𑱃𑰫𑰰𑰎𑰿𑰬𑰰𑰝𑰾𑱃𑰭𑰨𑰿𑰪𑰫𑰯𑰭𑰿𑰝𑰿𑰨𑰸𑰬𑰲𑱃𑰩𑰰𑰢𑰰𑰫𑰯𑰩𑰯𑰦𑰲𑰢𑰯𑰐𑰝𑰾𑱁𑱃𑰧𑰸𑰬𑰯𑰦𑰮𑰽𑱃𑰡𑰯𑰦𑰠𑰸𑰧𑰽𑱃𑰩𑰰𑰢𑰱𑰡𑰯𑰽𑱃𑰡𑱃𑰢𑰿𑰨𑰕𑰯𑰡𑰦𑰰𑱁𑱃𑰝𑰝𑰿𑰨𑰹𑰬𑱃𑰫𑰰𑰎𑰿𑰬𑰰𑰝𑰾𑱃𑰭𑰡𑰿𑰝𑰺𑱃𑰩𑰰𑰢𑰰𑰫𑰯𑰩𑰯𑰦𑰲𑰢𑰯𑰐𑰝𑰾𑱁

Probably, I should have added the translation as well:

“How wonderful! Even though the Pure Being
Is learned in all topics in the world,
He follows the conventions of the world.
Thus he has come to school.

“He has learned scripts
Even the names of which
I have not heard,
Yet he has come to school.

https://read.84000.co/translation/toh95.html#UT22084-046-001-557 (Verse 10.10 and Verse 10.11)

V

**Comment by r12a** [comment]
Added !  Thanks again.
https://r12a.github.io/scripts/fontlist/?script=bhks#result
