### ISSUE TITLE
[fontlist]  Linear B samples

### ISSUE THREAD

**Issue by tech189** [r12a/scripts#87]
[source] https://r12a.github.io/scripts/fontlist

**PY Ta 641 (palm-leaf tablet)** 

Text:

```
line 1
𐀴𐀪𐀡𐀆𐄀𐁁𐀐𐀄𐄀𐀐𐀩𐀯𐀍𐄀𐀸𐀐 𐃠 𐄈 𐀴𐀪𐀡𐄀𐀁𐀕𐄀𐀡𐀆𐄀𐀃𐀺𐀸 𐃠 𐄇 𐀴𐀪𐀡𐄀𐀐𐀩𐀯𐀍𐄀𐀸𐀐𐄀𐀀𐀢𐄀𐀐𐀏𐀄𐀕𐀜[ \𐀐𐀩𐁀 𐃠[/

line 2
𐀤𐀵 𐃢 𐄉 𐀇𐀞𐄀𐀕𐀿𐀁𐄀𐀤𐀵𐀫𐀸 𐃡 𐄇 𐀇𐀞𐀁𐄀𐀕𐀿𐀁𐄀𐀴𐀪𐀃𐀸𐀁 𐃡 𐄈 𐀇𐀞𐄀𐀕𐀹𐀍𐄀𐀤𐀵𐀫𐀸 𐃡 𐄇 [

line 3
𐀇𐀞𐄀𐀕𐀹𐀍𐄀𐀴𐀪𐀍𐀸 𐃡 𐄇 𐀇𐀞𐄀𐀕𐀹𐀍𐄀𐀀𐀜𐀸 𐃡 𐄇
```
Image here: http://calibra.classics.cam.ac.uk/Tablet/PY/641

Transcription:
```
line 1
ti-ri-po-de ai-ke-u ke-re-si-jo we-ke *201VAS 2  ti-ri-po e-me po-de o-wo-we *201VAS 1 ti-ri-po ke-re-si-jo we-ke a-pu ke-ka-u-me-no[ \ke-re-a2 *201VAS[/

line 2
qe-to *203VAS 3 di-pa me-zo-e qe-to-ro-we *202VAS 1  di-pa-e me-zo-e ti-ri-o-we-e *202VAS 2  di-pa me-wi-jo qe-to-ro-we *202VAS 1 [

line 3
di-pa me-wi-jo ti-ri-jo-we *202VAS 1 di-pa me-wi-jo a-no-we *202VAS 1
```

Translation:
```
line 1
"Two Aigeus tripods of Cretan workmanship; one tripod with one foot with one handle; one tripod of Cretan workmanship burnt from \the legs/ [

line 2
three pithos jars; one bigger goblet with four handles; two bigger goblets with three handles; one smaller goblet with four handles [

line 3
one smaller goblet with three handles; one smaller goblet with no handles."
```

Notes:
Discovered in 1952, it was important proof that Ventris' decipherment of Linear B was correct. Shows the level of detail the scribes went to in cataloguing.

**PY Ae 303 (palm-leaf tablet)**

Text:
```
        𐀂𐀋𐀫𐀍
𐀢𐀫𐄀𐀂𐀋𐀩𐀊𐄀𐀈𐀁𐀨𐄀𐀁𐀚𐀏𐄀𐀓𐀬𐀰𐀍    𐂁 𐄐𐄊[
```
(the word at the top is written in the middle of tablet, see image [here](http://calibra.classics.cam.ac.uk/Tablet/PY/303))

Transcription:
```
                    i-je-ro-jo
pu-ro i-je-re-ja do-e-ra e-ne-ka ku-ru-so-jo   MUL 14[
```

Translation:
```
"At Pylos: female slaves of the priestess on account of sacred gold: 14+"
```

Notes:
Meaning is unclear, the gold might be being bought or protected by slaves. Ventris & Chadwick (1973) pg. 166: "The nature of the transaction is obscure; were the slaves given to the priestess in return for some gold which had been offered? Or are they allocated to look after the gold ritual objects?"

**Comment by r12a** [comment]
Done !  Thanks.
Your contributor acknowledgment currently says tech189. Do you want me to change that?

**Comment by tech189** [comment]
No problem. 'tech189' without the @ please, if you don't mind!
Also just noticed, it looks like the backslashes are being removed on the page? Could you maybe replace them with fullwidth ＼ and ／? (They are to indicate an insertion from above the text by the scribe)

**Comment by r12a** [comment]
Fixed. The samples are stored in a list of json-like strings, so the \ needed to be escaped.  Should look ok now, without needing to resort to the fullwidth hack.

Closing this, then.  Reopen if there are additional issues.
