### ISSUE TITLE
[lao] Missing New Lao Characters..

### ISSUE THREAD

**Issue by Jayasiri-Jayasaro** [r12a/scripts#9]
Comment on http://r12a.github.io/scripts/lao/

Hi, there is a new Lao characters has been add on in the unicode v13 (https://unicode.org/charts/PDF/U0E80.pdf)

**Comment by r12a** [comment]
@loltipitaka I think you're referring to the 15 additions in Unicode 12 for writing Pali and Sanskrit (?).   If so, they are listed at https://r12a.github.io/scripts/lao/index.html#otherletters under 'Other letters'.  I don't have a font that supports these characters yet, so they appear as tofu.

**Comment by Jayasiri-Jayasaro** [comment]
This is the latest unicode LAO font.
