### ISSUE TITLE
[Syriac] Western Assyrian script used for Eastern description of the above and below majleaneh

### ISSUE THREAD

**Issue by SargisYonan** [r12a/scripts#98]
The characters after the "->" should use the "aii" script instead of the "tru" script for these examples. 

<img width="668" alt="Screen Shot 2021-08-03 at 8 36 50 PM" src="https://user-images.githubusercontent.com/5349027/128118390-2604891f-7c51-4be4-bea9-df2bb9d52b2a.png">
<img width="693" alt="Screen Shot 2021-08-03 at 8 37 34 PM" src="https://user-images.githubusercontent.com/5349027/128118443-3b41fc1d-4913-4510-b6b8-33a9ff518ba3.png">

Patch attached. 
[syriac_majleana_aii.txt](https://github.com/r12a/scripts/files/6928432/syriac_majleana_aii.txt)

**Comment by r12a** [comment]
Thanks for pointing that out. Sorry to take so long to fix it.  Now done. (Also a few other, less obvious, locations fixed by converting tru to aii.)
